package grack.dev.creditpointapp.features.dashboard.ui.kelas.detailsiswa

class DetailSiswaModel(
  var alamat: String?,
  var alamatAyah: String?,
  var alamatIbu: String?,
  var alamatWali: String?,
  var anakKe: String?,
  var createdBy: String?,
  var createdDate: String?,
  var deletedBy: Any?,
  var deletedDate: Any?,
  var idKelas: String?,
  var idSiswa: String?,
  var isDeleted: String?,
  var jenisKelamin: String?,
  var jumlahSaudara: String?,
  var nama: String?,
  var namaAyah: String?,
  var namaIbu: String?,
  var namaWali: String?,
  var noTelp: String?,
  var noTelpAyah: String?,
  var noTelpIbu: String?,
  var noTelpWali: String?,
  var pekerjaanAyah: String?,
  var pekerjaanIbu: String?,
  var pekerjaanWali: String?,
  var penghasilanAyah: String?,
  var penghasilanIbu: String?,
  var penghasilanWali: String?,
  var tempatLahir: String?,
  var tglLahir: String?,
  var updatedBy: Any?,
  var updatedDate: Any?
)